### ISSUE TITLE
Ябланица - SVG, EPS & PDF

### ISSUE THREAD

**Issue by dphilipov** [XenBG/bulgarian-city-coat-of-arms#10]
Векторизирано лого на Ябланица. Архив с всички файлове: [Yablanitsa.zip](https://github.com/XenBG/bulgarian-city-coat-of-arms/files/11488805/Yablanitsa.zip)

![Yablanitsa](https://github.com/XenBG/bulgarian-city-coat-of-arms/assets/76788928/e01df4a1-2fd4-472f-a2e2-4271c323d35d)

**Comment by XenBG** [comment]
Файловете са добавени в хранилището. Благодаря!
