### ISSUE TITLE
Угърчин - SVG, EPS & PDF

### ISSUE THREAD

**Issue by dphilipov** [XenBG/bulgarian-city-coat-of-arms#11]
Векторизирано лого на Угърчин. Архив с всички файлове: [Ugarchin.zip](https://github.com/XenBG/bulgarian-city-coat-of-arms/files/11489112/Ugarchin.zip)

![Ugarchin](https://github.com/XenBG/bulgarian-city-coat-of-arms/assets/76788928/66277a8d-87b4-48b0-873a-25e2a8d63496)

**Comment by XenBG** [comment]
Файловете са добавени в хранилището. Благодаря!
