### ISSUE TITLE
Белене - SVG, EPS & PDF

### ISSUE THREAD

**Issue by dphilipov** [XenBG/bulgarian-city-coat-of-arms#13]
Векторизирана версия на герба на [община Белене](https://belene.bg/gerb-i-simvoli/).

Архив с файловете: [Belene.zip](https://github.com/XenBG/bulgarian-city-coat-of-arms/files/11500837/Belene.zip)

![Belene](https://github.com/XenBG/bulgarian-city-coat-of-arms/assets/76788928/33e92969-0076-4315-83f9-161584cb0bf6)

**Comment by XenBG** [comment]
Файловете са добавени в хранилището. Благодаря!
