### ISSUE TITLE
Isperih - SVG

### ISSUE THREAD

**Issue by emiltoteb** [XenBG/bulgarian-city-coat-of-arms#3]
![isperih-coat-of-arms](https://user-images.githubusercontent.com/33400755/197046572-03c6c2ae-03f1-43fa-af37-ff0c26566ff2.svg)

Имам този, изостанал от един проект, не е оптимален, има няколко проблема при буквите, както и горе при житния клас, но за дребни размери, както и беше използван, а и за поне някакво наличие тук смятам става.  Качвам as-is, без намеса от моя страна.

Успех!

**Comment by XenBG** [comment]
Здравей, случайно да разполагаш с `.ai`, `.cdr` или `.eps` версия? `.svg`-то е с доста лошо качество и при опит да го конвертирам в друг формат, крайният резултат не е добър. Изглежда пикселизиран и много малък.

**Comment by emiltoteb** [comment]
Опитай с тези тук, че качването в горния коментар се е счупило някъде по веригата - https://u.pcloud.link/publink/show?code=kZLWJuVZRWzpcgqu06Lhjlox9e0oIHmwicMk

**Comment by XenBG** [comment]
Файлът изглежда наред и успешно успях да го конвертирам в .svg, .pdf и .eps. Благодаря ти! # #
