### ISSUE TITLE
Трън - SVG, EPS & PDF

### ISSUE THREAD

**Issue by dphilipov** [XenBG/bulgarian-city-coat-of-arms#5]
Векторизирана версия на емблемата от сайта на [община Трън](https://tran.egov.bg/wps/portal/municipality-tran/municipality/symbols-honorable-citizens/symbols)

SVG: 
![Tran](https://github.com/XenBG/bulgarian-city-coat-of-arms/assets/76788928/304993e1-d3b8-4996-ab97-2df62e75e904)

EPS:
[Tran.zip](https://github.com/XenBG/bulgarian-city-coat-of-arms/files/11475768/Tran.zip)

PDF:
[Tran.pdf](https://github.com/XenBG/bulgarian-city-coat-of-arms/files/11475765/Tran.pdf)

**Comment by XenBG** [comment]
Файловете са добавени в хранилището. Благодаря!
