### ISSUE TITLE
Хисаря - SVG, EPS & PDF

### ISSUE THREAD

**Issue by dphilipov** [XenBG/bulgarian-city-coat-of-arms#6]
Векторизирана версия на емблемата от сайта на [община Хисаря](https://hisarya.bg/)

SVG:
![Hisarya](https://github.com/XenBG/bulgarian-city-coat-of-arms/assets/76788928/153a2daa-b22e-4cbf-a860-2fa9b28da160)

EPS:
[Hisarya.zip](https://github.com/XenBG/bulgarian-city-coat-of-arms/files/11470388/Hisarya.zip)

PDF:
[Hisarya.pdf](https://github.com/XenBG/bulgarian-city-coat-of-arms/files/11470386/Hisarya.pdf)

**Comment by XenBG** [comment]
Файловете са добавени в хранилището. Благодаря!
