### ISSUE TITLE
Лясковец - SVG, EPS & PDF

### ISSUE THREAD

**Issue by dphilipov** [XenBG/bulgarian-city-coat-of-arms#9]
Векторизирана версия на емблемата от сайта на [община Лясковец](https://www.lyaskovets.bg/d1_tm6_symbols.php). Автор е **Марчо Караджов**.

SVG:
![Lyaskovetz](https://github.com/XenBG/bulgarian-city-coat-of-arms/assets/76788928/ddc96988-2d91-4b93-a846-2f7d48d47480)

EPS:
[Lyaskovetz.zip](https://github.com/XenBG/bulgarian-city-coat-of-arms/files/11471627/Lyaskovetz.zip)

PDF:
[Lyaskovetz.pdf](https://github.com/XenBG/bulgarian-city-coat-of-arms/files/11471626/Lyaskovetz.pdf)

**Comment by XenBG** [comment]
Файловете са добавени в хранилището. Благодаря!
